tasks:
  - init: |
      sudo apt-get update
      sudo DEBIAN_FRONTEND=noninteractive apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y --fix-missing
      npm install -g pnpm
      pnpm install
